DROP TABLE LIKE_COUNT purge;
DROP TABLE WARN purge;
DROP TABLE IMAGE_LIKE purge;
DROP TABLE COMMENTS purge;

DROP TABLE BOARD purge;

DROP TABLE IMAGE purge;
DROP TABLE MEMBER purge;

create TABLE MEMBER(
M_ID		VARCHAR2(13) PRIMARY KEY,
M_NAME		VARCHAR2(13) UNIQUE,
M_AGES		NUMBER(2),
M_GENDER	varchar2(1), /*f ,m*/
M_PASS		VARCHAR2(30),
M_MAIL		VARCHAR2(30) UNIQUE,
M_TAG1		varchar2(10) ,
M_TAG2		varchar2(10) ,
M_TAG3		varchar2(10) ,
M_TAG4		varchar2(10) ,
M_TAG5		varchar2(10) ,
M_LIKECOUNT	number(30) DEFAULT 0
);

CREATE TABLE BOARD(
B_NUM		NUMBER(38) PRIMARY KEY,
B_ID		VARCHAR2(13),
B_PASS		VARCHAR2(20),
B_TITLE		VARCHAR2(100),
B_CONTENT	VARCHAR2(3000),
B_DATE		DATE,
B_VIEW		NUMBER(38) DEFAULT 0,
B_TAG		varchar2(20),
FOREIGN KEY (B_ID)
REFERENCES MEMBER(M_ID) ON DELETE CASCADE
);

CREATE TABLE IMAGE(
I_NUM		NUMBER(38) PRIMARY KEY,
M_ID 		VARCHAR2(13),
FILENAME	VARCHAR2(30),
I_TAG1		varchar2(10) DEFAULT 0,
I_TAG2		varchar2(10) DEFAULT 0,
I_TAG3		varchar2(10) DEFAULT 0,
I_TAG4		varchar2(10) DEFAULT 0,
I_TAG5		varchar2(10) DEFAULT 0,
I_CONTENT	VARCHAR2(100),
I_DATE		DATE,
I_LATIUDE	NUMBER,
I_LONGTITUDE NUMBER,
I_LIKECOUNT	NUMBER(38) DEFAULT 0,
FOREIGN KEY (M_ID)
REFERENCES MEMBER(M_ID) ON DELETE CASCADE
);


CREATE TABLE COMMENTS(
C_NUM		NUMBER(38) PRIMARY KEY,
B_NUM		NUMBER(38),
I_NUM		NUMBER(38),
M_ID		VARCHAR2(13),
C_CONTENT	VARCHAR2(500),
C_DATE		DATE,
FOREIGN KEY (B_NUM)
REFERENCES BOARD(B_NUM) ON DELETE CASCADE,
FOREIGN KEY (I_NUM)
REFERENCES IMAGE(I_NUM) ON DELETE CASCADE,
FOREIGN KEY (M_ID)
REFERENCES MEMBER(M_ID) ON DELETE CASCADE
);


CREATE TABLE IMAGE_LIKE(
I_NUM 		NUMBER(38) PRIMARY KEY,
MALE_COUNT	NUMBER(38) DEFAULT 0,
FEMALE_COUNT	NUMBER(38) DEFAULT 0,
YEAR_10		NUMBER(38) DEFAULT 0,
YEAR_20		NUMBER(38) DEFAULT 0,
YEAR_30		NUMBER(38) DEFAULT 0,
YEAR_40		NUMBER(38) DEFAULT 0,
YEAR_50		NUMBER(38) DEFAULT 0,
FOREIGN KEY (I_NUM)
REFERENCES IMAGE(I_NUM) ON DELETE CASCADE
);


create table warn(
M_ID		varchar2(13),
I_NUM		number(38),
B_NUM		number(38),
C_NUM		number(38),
W_TAG1		varchar2(10),
W_TAG2		varchar2(10),
W_COUNT		number(38),
FOREIGN KEY (M_ID)
REFERENCES MEMBER(M_ID) ON DELETE CASCADE,
FOREIGN KEY (I_NUM)
REFERENCES IMAGE(I_NUM) ON DELETE CASCADE,
FOREIGN KEY (B_NUM)
REFERENCES BOARD(B_NUM) ON DELETE CASCADE,
FOREIGN KEY (C_NUM)
REFERENCES COMMENTS(C_NUM) ON DELETE CASCADE
);

create table LIKE_COUNT(
ID varchar2(13),
I_NUM number(38),
Click number(20),
FOREIGN KEY (I_NUM)
REFERENCES IMAGE(I_NUM) ON DELETE CASCADE
);


insert into member values('admin','관리자',22,'M','1','gi5825@gmail.com',0,0,0,0,0,0);
insert into member values('user1','유저일',23,'M','1','gi5826@gmail.com',1,0,0,1,0,0);
insert into member values('user2','유저이',23,'F','1','gi5827@gmail.com',1,1,1,1,0,0);
insert into member values('user3','유저삼',23,'M','1','gi5828@gmail.com',0,1,0,0,1,0);
insert into member values('user4','유저사',23,'F','1','gi5829@gmail.com',1,1,0,1,1,0);